// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: zetsu/zetsu.proto

package zetsu

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ConfigItem_MonitorItemType int32

const (
	ConfigItem_CPU ConfigItem_MonitorItemType = 0
	ConfigItem_MEM ConfigItem_MonitorItemType = 1
	ConfigItem_NET ConfigItem_MonitorItemType = 2
)

// Enum value maps for ConfigItem_MonitorItemType.
var (
	ConfigItem_MonitorItemType_name = map[int32]string{
		0: "CPU",
		1: "MEM",
		2: "NET",
	}
	ConfigItem_MonitorItemType_value = map[string]int32{
		"CPU": 0,
		"MEM": 1,
		"NET": 2,
	}
)

func (x ConfigItem_MonitorItemType) Enum() *ConfigItem_MonitorItemType {
	p := new(ConfigItem_MonitorItemType)
	*p = x
	return p
}

func (x ConfigItem_MonitorItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigItem_MonitorItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_zetsu_zetsu_proto_enumTypes[0].Descriptor()
}

func (ConfigItem_MonitorItemType) Type() protoreflect.EnumType {
	return &file_zetsu_zetsu_proto_enumTypes[0]
}

func (x ConfigItem_MonitorItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigItem_MonitorItemType.Descriptor instead.
func (ConfigItem_MonitorItemType) EnumDescriptor() ([]byte, []int) {
	return file_zetsu_zetsu_proto_rawDescGZIP(), []int{1, 0}
}

type MachineBasicInfo_CPUArch int32

const (
	MachineBasicInfo_X86_64  MachineBasicInfo_CPUArch = 0
	MachineBasicInfo_AARCH64 MachineBasicInfo_CPUArch = 1
	MachineBasicInfo_X86     MachineBasicInfo_CPUArch = 2
)

// Enum value maps for MachineBasicInfo_CPUArch.
var (
	MachineBasicInfo_CPUArch_name = map[int32]string{
		0: "X86_64",
		1: "AARCH64",
		2: "X86",
	}
	MachineBasicInfo_CPUArch_value = map[string]int32{
		"X86_64":  0,
		"AARCH64": 1,
		"X86":     2,
	}
)

func (x MachineBasicInfo_CPUArch) Enum() *MachineBasicInfo_CPUArch {
	p := new(MachineBasicInfo_CPUArch)
	*p = x
	return p
}

func (x MachineBasicInfo_CPUArch) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineBasicInfo_CPUArch) Descriptor() protoreflect.EnumDescriptor {
	return file_zetsu_zetsu_proto_enumTypes[1].Descriptor()
}

func (MachineBasicInfo_CPUArch) Type() protoreflect.EnumType {
	return &file_zetsu_zetsu_proto_enumTypes[1]
}

func (x MachineBasicInfo_CPUArch) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineBasicInfo_CPUArch.Descriptor instead.
func (MachineBasicInfo_CPUArch) EnumDescriptor() ([]byte, []int) {
	return file_zetsu_zetsu_proto_rawDescGZIP(), []int{5, 0}
}

type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Info   string `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zetsu_zetsu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zetsu_zetsu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_zetsu_zetsu_proto_rawDescGZIP(), []int{0}
}

func (x *StatusResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StatusResponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type ConfigItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value     float64                    `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Type      ConfigItem_MonitorItemType `protobuf:"varint,2,opt,name=type,proto3,enum=zetsu.ConfigItem_MonitorItemType" json:"type,omitempty"`
	Timestamp int32                      `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ConfigItem) Reset() {
	*x = ConfigItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zetsu_zetsu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItem) ProtoMessage() {}

func (x *ConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_zetsu_zetsu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItem.ProtoReflect.Descriptor instead.
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return file_zetsu_zetsu_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigItem) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ConfigItem) GetType() ConfigItem_MonitorItemType {
	if x != nil {
		return x.Type
	}
	return ConfigItem_CPU
}

func (x *ConfigItem) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interval    int32         `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	MaxSaveTime int32         `protobuf:"varint,2,opt,name=max_save_time,json=maxSaveTime,proto3" json:"max_save_time,omitempty"`
	Items       []*ConfigItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zetsu_zetsu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zetsu_zetsu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_zetsu_zetsu_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigResponse) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *ConfigResponse) GetMaxSaveTime() int32 {
	if x != nil {
		return x.MaxSaveTime
	}
	return 0
}

func (x *ConfigResponse) GetItems() []*ConfigItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MonitorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items   []*ConfigItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	EndTime int32         `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *MonitorInfo) Reset() {
	*x = MonitorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zetsu_zetsu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonitorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorInfo) ProtoMessage() {}

func (x *MonitorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_zetsu_zetsu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorInfo.ProtoReflect.Descriptor instead.
func (*MonitorInfo) Descriptor() ([]byte, []int) {
	return file_zetsu_zetsu_proto_rawDescGZIP(), []int{3}
}

func (x *MonitorInfo) GetItems() []*ConfigItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MonitorInfo) GetEndTime() int32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type MachineConnectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri     string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	GroupId int32  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *MachineConnectInfo) Reset() {
	*x = MachineConnectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zetsu_zetsu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineConnectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineConnectInfo) ProtoMessage() {}

func (x *MachineConnectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_zetsu_zetsu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineConnectInfo.ProtoReflect.Descriptor instead.
func (*MachineConnectInfo) Descriptor() ([]byte, []int) {
	return file_zetsu_zetsu_proto_rawDescGZIP(), []int{4}
}

func (x *MachineConnectInfo) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *MachineConnectInfo) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type MachineBasicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuArch    MachineBasicInfo_CPUArch `protobuf:"varint,1,opt,name=cpu_arch,json=cpuArch,proto3,enum=zetsu.MachineBasicInfo_CPUArch" json:"cpu_arch,omitempty"`
	CpuCores   int32                    `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemorySize int32                    `protobuf:"varint,3,opt,name=memory_size,json=memorySize,proto3" json:"memory_size,omitempty"`
	OsType     string                   `protobuf:"bytes,4,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
}

func (x *MachineBasicInfo) Reset() {
	*x = MachineBasicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zetsu_zetsu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineBasicInfo) ProtoMessage() {}

func (x *MachineBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_zetsu_zetsu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineBasicInfo.ProtoReflect.Descriptor instead.
func (*MachineBasicInfo) Descriptor() ([]byte, []int) {
	return file_zetsu_zetsu_proto_rawDescGZIP(), []int{5}
}

func (x *MachineBasicInfo) GetCpuArch() MachineBasicInfo_CPUArch {
	if x != nil {
		return x.CpuArch
	}
	return MachineBasicInfo_X86_64
}

func (x *MachineBasicInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *MachineBasicInfo) GetMemorySize() int32 {
	if x != nil {
		return x.MemorySize
	}
	return 0
}

func (x *MachineBasicInfo) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

var File_zetsu_zetsu_proto protoreflect.FileDescriptor

var file_zetsu_zetsu_proto_rawDesc = []byte{
	0x0a, 0x11, 0x7a, 0x65, 0x74, 0x73, 0x75, 0x2f, 0x7a, 0x65, 0x74, 0x73, 0x75, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x7a, 0x65, 0x74, 0x73, 0x75, 0x22, 0x3c, 0x0a, 0x0e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xa5, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x35, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x7a, 0x65,
	0x74, 0x73, 0x75, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x4d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x2c, 0x0a, 0x0f, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x49, 0x74, 0x65,
	0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x50, 0x55, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x4d, 0x45, 0x4d, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x54, 0x10, 0x02,
	0x22, 0x79, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x22,
	0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x53, 0x61, 0x76, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x7a, 0x65, 0x74, 0x73, 0x75, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x51, 0x0a, 0x0b, 0x4d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x27, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x7a, 0x65, 0x74, 0x73,
	0x75, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x41,
	0x0a, 0x12, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x22, 0xd2, 0x01, 0x0a, 0x10, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3a, 0x0a, 0x08, 0x63, 0x70, 0x75, 0x5f, 0x61, 0x72,
	0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x7a, 0x65, 0x74, 0x73, 0x75,
	0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x43, 0x50, 0x55, 0x41, 0x72, 0x63, 0x68, 0x52, 0x07, 0x63, 0x70, 0x75, 0x41, 0x72,
	0x63, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x70, 0x75, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x70, 0x75, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x6f, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2b, 0x0a, 0x07, 0x43, 0x50, 0x55,
	0x41, 0x72, 0x63, 0x68, 0x12, 0x0a, 0x0a, 0x06, 0x58, 0x38, 0x36, 0x5f, 0x36, 0x34, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x41, 0x41, 0x52, 0x43, 0x48, 0x36, 0x34, 0x10, 0x01, 0x12, 0x07, 0x0a,
	0x03, 0x58, 0x38, 0x36, 0x10, 0x02, 0x32, 0xd5, 0x01, 0x0a, 0x05, 0x5a, 0x65, 0x74, 0x73, 0x75,
	0x12, 0x45, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x12, 0x19, 0x2e, 0x7a, 0x65, 0x74, 0x73, 0x75, 0x2e, 0x4d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x15,
	0x2e, 0x7a, 0x65, 0x74, 0x73, 0x75, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x17, 0x2e, 0x7a, 0x65, 0x74,
	0x73, 0x75, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x15, 0x2e, 0x7a, 0x65, 0x74, 0x73, 0x75, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x11,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x12, 0x2e, 0x7a, 0x65, 0x74, 0x73, 0x75, 0x2e, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x15, 0x2e, 0x7a, 0x65, 0x74, 0x73, 0x75, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x19,
	0x5a, 0x17, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x79, 0x7a,
	0x69, 0x64, 0x75, 0x2f, 0x7a, 0x65, 0x74, 0x73, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_zetsu_zetsu_proto_rawDescOnce sync.Once
	file_zetsu_zetsu_proto_rawDescData = file_zetsu_zetsu_proto_rawDesc
)

func file_zetsu_zetsu_proto_rawDescGZIP() []byte {
	file_zetsu_zetsu_proto_rawDescOnce.Do(func() {
		file_zetsu_zetsu_proto_rawDescData = protoimpl.X.CompressGZIP(file_zetsu_zetsu_proto_rawDescData)
	})
	return file_zetsu_zetsu_proto_rawDescData
}

var file_zetsu_zetsu_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_zetsu_zetsu_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_zetsu_zetsu_proto_goTypes = []interface{}{
	(ConfigItem_MonitorItemType)(0), // 0: zetsu.ConfigItem.MonitorItemType
	(MachineBasicInfo_CPUArch)(0),   // 1: zetsu.MachineBasicInfo.CPUArch
	(*StatusResponse)(nil),          // 2: zetsu.StatusResponse
	(*ConfigItem)(nil),              // 3: zetsu.ConfigItem
	(*ConfigResponse)(nil),          // 4: zetsu.ConfigResponse
	(*MonitorInfo)(nil),             // 5: zetsu.MonitorInfo
	(*MachineConnectInfo)(nil),      // 6: zetsu.MachineConnectInfo
	(*MachineBasicInfo)(nil),        // 7: zetsu.MachineBasicInfo
}
var file_zetsu_zetsu_proto_depIdxs = []int32{
	0, // 0: zetsu.ConfigItem.type:type_name -> zetsu.ConfigItem.MonitorItemType
	3, // 1: zetsu.ConfigResponse.items:type_name -> zetsu.ConfigItem
	3, // 2: zetsu.MonitorInfo.items:type_name -> zetsu.ConfigItem
	1, // 3: zetsu.MachineBasicInfo.cpu_arch:type_name -> zetsu.MachineBasicInfo.CPUArch
	6, // 4: zetsu.Zetsu.RegisterMonitor:input_type -> zetsu.MachineConnectInfo
	7, // 5: zetsu.Zetsu.GetLatestConfig:input_type -> zetsu.MachineBasicInfo
	5, // 6: zetsu.Zetsu.UploadMonitorItem:input_type -> zetsu.MonitorInfo
	2, // 7: zetsu.Zetsu.RegisterMonitor:output_type -> zetsu.StatusResponse
	4, // 8: zetsu.Zetsu.GetLatestConfig:output_type -> zetsu.ConfigResponse
	2, // 9: zetsu.Zetsu.UploadMonitorItem:output_type -> zetsu.StatusResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_zetsu_zetsu_proto_init() }
func file_zetsu_zetsu_proto_init() {
	if File_zetsu_zetsu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zetsu_zetsu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zetsu_zetsu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zetsu_zetsu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zetsu_zetsu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonitorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zetsu_zetsu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineConnectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zetsu_zetsu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachineBasicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zetsu_zetsu_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zetsu_zetsu_proto_goTypes,
		DependencyIndexes: file_zetsu_zetsu_proto_depIdxs,
		EnumInfos:         file_zetsu_zetsu_proto_enumTypes,
		MessageInfos:      file_zetsu_zetsu_proto_msgTypes,
	}.Build()
	File_zetsu_zetsu_proto = out.File
	file_zetsu_zetsu_proto_rawDesc = nil
	file_zetsu_zetsu_proto_goTypes = nil
	file_zetsu_zetsu_proto_depIdxs = nil
}
